# Debian・Ubuntu向け設定
- block:
  - name: Set timezone to Asia/Tokyo
    file:
      src: /usr/share/zoneinfo/Asia/Tokyo
      path: /etc/localtime
      state: link
      force: yes
    notify:
      - update timezone
  # Debian・Ubuntu向け設定ここまで
  when: "ansible_os_family == 'Debian'"

# CentOS向け設定
- block:
  - name: Set timezone to Japan
    file:
      src: /usr/share/zoneinfo/Japan
      path: /etc/localtime
      state: link
      force: yes
  # CentOS向けここまで
  when: "ansible_os_family == 'RedHat'"
